linkPrefix = ''
# linkPrefix = '/numenta-web'  # integration/staging (gh-pages)

siteHost = 'Numenta.org'
siteTitle = 'Hierarchical Temporal Memory (HTM)'
description = 'Home of the HTM Community'
company = 'Numenta'

[contact]
  [contact.email]
    info = 'info@numenta.org'

[analytics]
  google = 'UA-40622508-1'
  pingdom = '55a7dbc8abe53dba666b928b'

[links]
  [links.out]  # external links
    papers = 'https://numenta.com/papers'
    columnsPaper = 'https://numenta.com/neuroscience-research/research-publications/papers/a-theory-of-how-columns-in-the-neocortex-enable-learning-the-structure-of-the-world/'
    bami = 'https://numenta.com/resources/biological-and-machine-intelligence/'
    com = 'https://numenta.com/'
    cortical = 'https://cortical.io/'
    github = 'https://github.com/numenta'
    communityGithub = 'https://github.com/htm-community'
    grok = 'https://grokstream.com/'
    forum = 'https://discourse.numenta.org/categories'
    meetup = 'https://www.meetup.com/Numenta-Platform-for-Intelligent-Computing-Events/'
    onintelligence = 'https://numenta.com/resources/papers-videos-and-more/on-intelligence/'
    youtube = 'https://www.youtube.com/user/OfficialNumenta'
    latestSchool = 'https://www.youtube.com/watch?v=LNRZD9YJCdI'
    latestSchoolThumb = 'https://i3.ytimg.com/vi/LNRZD9YJCdI/mqdefault.jpg'
    spLinks = 'https://numenta.com/resources/biological-and-machine-intelligence/spatial-pooling-algorithm/'
    tmLinks = 'https://numenta.com/resources/biological-and-machine-intelligence/temporal-memory-algorithm/'

  [links.in]  # internal paths
    # main/home pseudo-single page
    home = '/'
    community = '/community/'
    htm = '/hierarchical-temporal-memory/'
    code = '/code/'
    # other site pages
    school = '/htm-school/'
    blog = '/blog/'
    conduct = '/licenses/conduct/'
    contrib = '/licenses/contrib/'
    implement = '/implementations/'
    license = '/licenses/'
    privacy = '/legal/privacy/'
    sitemap = '/sitemap/'
    terms = '/legal/terms/'
    trial = '/licenses/trial/'

[moments]
  post = 'YYYY/MM/DD'
  human = 'ddd, MMM DD, YYYY'
